### ISSUE TITLE
sometimes randomly failing tests

### ISSUE THREAD

**Issue by tothimre-zz** [Trismegiste/Mondrian#21] opened 2013-05-28 13:04 UTC
The issue due to this test:

trismegiste/mondrian/Trismegiste/Mondrian/Tests/Graph/SearchPathTest.php:86

**Comment by Trismegiste** [comment] 2013-05-29 08:29
I know where the problem is. It's a bug in the test itself. There is a randomly generated graph and sometime nodes don't connect if you have no luck.

**Comment by Trismegiste** [comment] 2013-05-30 08:05
fixed by ac4779cb8c4536bf2070af95c6da0295a7fa1193

**Closed as completed by Trismegiste** 2013-05-30 08:05 UTC
Labels: bug
